[package]
name = "edit_anki"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "edit_anki"
crate-type = ["cdylib","rlib"]

[dependencies]
anki = { path = "anki/rslib" }

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "abi3", "abi3-py39"]

